web:
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - ./docker/nginx/conf.d:/etc/nginx/conf.d
    - ./:/code/
  links:
    - php

php:
  build: ./docker/php
  volumes:
    - ./:/code/
  links:
    - db:db

db:
  image: mysql:8
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: root
