index:
  path: /
  methods: [GET]
  controller: App\Controller\MainController::index

cv:
  path: /curriculum-vitae
  methods: [GET]
  controller: App\Controller\MainController::curriculumVitae

contact:
  path: /contact
  methods: [POST]
  controller: App\Controller\MainController::contact
